-- Databricks notebook source
-- Generated for: SCRUM-66
-- Universal Plan Schema generation
--
-- Query 1: d_customer_transformation
--   Pattern: dimension_flat

/**************************************************************************
Generated plan for d_customer dimension table.
**************************************************************************/

-- Query: d_customer_transformation
-- Pattern: dimension_flat
-- Coverage: 169 rows

SELECT
  concat('msd_qad_', lower(ad_mstr.ad_domain)) AS cust_key,
  concat('msd_qad_', lower(ad_mstr.ad_domain)) AS src_sys_cd,
  cm_mstr.cm_addr AS cust_id,
  cm_mstr.ad_name AS cust_nm,
  cm_mstr.ad_name AS cust_nm_en,
  cm_mstr.ad_type AS cust_type_cd,
  cm_mstr.ad_type AS cust_type_nm,
  CAST(NULL AS string) AS active_flg,
  CAST(NULL AS string) AS parent_cust_id,
  CAST(NULL AS string) AS parent_cust_nm,
  CAST(NULL AS string) AS naics_cd,
  CAST(NULL AS string) AS naics_nm,
  CAST(NULL AS string) AS sic_cd,
  CAST(NULL AS string) AS sic_nm,
  CAST(NULL AS string) AS gbl_govt_id,
  CAST(NULL AS string) AS gbl_loc_nbr,
  CAST(NULL AS string) AS dnb_duns_nm,
  CAST(NULL AS string) AS alt_payer_cust_id,
  CAST(NULL AS string) AS annl_sls_amt,
  CAST(NULL AS string) AS central_bill_block_cd,
  CAST(NULL AS string) AS central_bill_block_nm,
  CAST(NULL AS string) AS central_delvr_block_cd,
  CAST(NULL AS string) AS central_delvr_block_nm,
  CAST(NULL AS string) AS central_ord_block_cd,
  CAST(NULL AS string) AS central_ord_block_nm,
  CAST(NULL AS string) AS cust_acct_grp_cd,
  CAST(NULL AS string) AS cust_acct_grp_nm,
  CAST(NULL AS string) AS cust_class_cd,
  CAST(NULL AS string) AS cust_class_nm,
  cm_mstr.cm_curr AS curncy_cd,
  cm_mstr.currencydescription AS curncy_nm,
  CAST(NULL AS string) AS indy_cd,
  CAST(NULL AS string) AS indy_nm,
  CAST(NULL AS string) AS intl_loc_nbr_check_digit,
  cm_mstr.ad_lang AS lang_cd,
  CAST(NULL AS string) AS lang_iso_cd,
  CAST(NULL AS string) AS lang_nm,
  CAST(NULL AS string) AS lgl_stat_cd,
  CAST(NULL AS string) AS lgl_stat_nm,
  CAST(NULL AS string) AS rgn_mkt,
  CAST(NULL AS string) AS sls_since_yr,
  cm_mstr.ad_sort AS sort_field,
  cm_mstr.ad_tax_usage AS tax_juris_cd,
  CAST(NULL AS string) AS tax_juris_nm,
  CAST(NULL AS string) AS teletex_nbr,
  CAST(NULL AS string) AS telex_nbr,
  CAST(NULL AS string) AS title,
  CAST(NULL AS string) AS transp_zone_cd,
  CAST(NULL AS string) AS transp_zone_nm,
  CAST(NULL AS string) AS trading_prtnr_co_cd,
  CAST(NULL AS string) AS url,
  CAST(NULL AS string) AS unload_point_flg,
  cm_mstr.ad_vat_reg AS vat_regstr_nbr,
  CAST(NULL AS string) AS central_del_block_flg,
  CAST(NULL AS string) AS central_del_flg,
  CAST(NULL AS string) AS central_post_block_flg,
  CAST(NULL AS string) AS central_sls_block_flg,
  CAST(NULL AS string) AS cmptr_flg,
  CAST(NULL AS string) AS natural_pers_flg,
  CAST(NULL AS string) AS one_time_cust_flg,
  CAST(NULL AS string) AS sls_prtnr_flg,
  CAST(NULL AS string) AS sls_prospect_flg,
  cm_mstr.ad_address_id AS addr_key,
  cm_mstr.ad_line2 AS street_line,
  cm_mstr.ad_zip AS pstl_cd,
  cm_mstr.ad_city AS city,
  CAST(NULL AS string) AS city_coord,
  CAST(NULL AS string) AS po_box,
  CAST(NULL AS string) AS po_box_pstl_cd,
  CAST(NULL AS string) AS district,
  cm_mstr.ad_state AS st_prov_cd,
  CAST(NULL AS string) AS st_prov_nm,
  cm_mstr.ad_ctry AS cntry_cd,
  cm_mstr.ad_country AS cntry_nm,
  cm_mstr.ad_fax AS fax_nbr,
  CAST(NULL AS string) AS trading_prtnr_co_nm,
  CAST(NULL AS string) AS prim_contact_key,
  CAST(NULL AS string) AS dnb_duns_nbr,
  cm_mstr.ad_line1 AS addr_nm_line2,
  cm_mstr.ad_line2 AS addr_nm_line3,
  cm_mstr.ad_line3 AS addr_nm_line4,
  CAST(NULL AS string) AS cust_cond_grp_cd1,
  CAST(NULL AS string) AS cust_cond_grp_cd2,
  CAST(NULL AS string) AS cust_cond_grp_nm1,
  CAST(NULL AS string) AS cust_cond_grp_nm2,
  cm_mstr.ad_email AS cust_email_addr_txt,
  CAST(NULL AS string) AS cust_rept_hier_base,
  CAST(NULL AS string) AS dw_src_key,
  CAST(NULL AS string) AS indy_cd1,
  CAST(NULL AS string) AS indy_cd2,
  CAST(NULL AS string) AS indy_nm1,
  CAST(NULL AS string) AS indy_nm2,
  CAST(NULL AS string) AS intl_loc_nbr1,
  CAST(NULL AS string) AS intl_loc_nbr2,
  cm_mstr.ad_phone AS phn_nbr1,
  cm_mstr.ad_phone2 AS phn_nbr2,
  CAST(NULL AS string) AS search_mcode1,
  CAST(NULL AS string) AS search_mcode2,
  CAST(NULL AS string) AS search_mcode3,
  CAST(NULL AS string) AS sply_center_cd,
  CAST(NULL AS string) AS sply_center_flg,
  CAST(NULL AS string) AS sply_center_nm,
  cm_mstr.ad_pst_id AS tax_nbr1,
  CAST(NULL AS string) AS tax_nbr2,
  CAST(NULL AS string) AS tax_nbr3,
  CAST(NULL AS string) AS src_crt_by,
  cm_mstr.ad_date AS src_crt_ts,
  cm_mstr.ad_userid AS src_updt_by,
  cm_mstr.cm_mod_date AS src_updt_ts,
  CAST(NULL AS string) AS rec_crt_ts,
  CAST(NULL AS string) AS rec_updt_ts,
  CAST(NULL AS string) AS stock_ticker_cd,
  CAST(NULL AS string) AS cdw_cust_key,
  CAST(NULL AS string) AS dw_cust_key,
  CAST(NULL AS string) AS addr_phn_nbr,
  cm_mstr.ad_fax2 AS addr_fax_nbr,
  CAST(NULL AS string) AS sls_chnl_cd,
  CAST(NULL AS string) AS sls_terr_cd,
  CAST(NULL AS string) AS sls_rep_cust_key,
  CAST(NULL AS string) AS addr_type_cd,
  CAST(NULL AS string) AS hfm_entity_key,
  CAST(NULL AS string) AS hfm_entity_cd,
  cm.cntry_hier_key AS deflt_delvr_cntry_key,
  cm.ad_ctry AS deflt_delvr_cntry_cd,
  CAST(NULL AS string) AS trade_chnl_cd,
  CASE WHEN cm.ad_addr LIKE 'Z%' OR cm.ad_addr LIKE 'TM%' THEN 'IC' ELSE '3rd' END AS inter_co_cd,
  CAST(NULL AS string) AS county,
  CAST(NULL AS string) AS temporary_flag,
  CAST(NULL AS string) AS bank_acct_1,
  CAST(NULL AS string) AS coc_number,
  CAST(NULL AS string) AS tax_id_federal,
  CAST(NULL AS string) AS tax_type,
  CAST(NULL AS string) AS tax_class_code,
  CAST(NULL AS string) AS taxable_flag,
  CAST(NULL AS string) AS tax_in_flag,
  CAST(NULL AS string) AS netting_logic,
  CAST(NULL AS string) AS trading_prtnr_interface_id,
  CAST(NULL AS string) AS edi_control,
  CAST(NULL AS string) AS time_zone,
  CAST(NULL AS string) AS trading_prtnr_edi_id,
  CAST(NULL AS string) AS barcode_label_print_program,
  CAST(NULL AS string) AS barcode_validation_program,
  CAST(NULL AS string) AS calendar,
  CAST(NULL AS string) AS edi_standard,
  CAST(NULL AS string) AS edi_standard_level,
  CAST(NULL AS string) AS trd_partner_location_code,
  CAST(NULL AS string) AS tax_zone,
  CAST(NULL AS string) AS tax_id_misc_1,
  CAST(NULL AS string) AS tax_id_misc_2,
  CAST(NULL AS string) AS tax_id_misc_3,
  CAST(NULL AS string) AS week_offset,
  CAST(NULL AS string) AS invoices_via,
  CAST(NULL AS string) AS schedules_via,
  CAST(NULL AS string) AS purchase_orders_via,
  CAST(NULL AS string) AS asn_default_data,
  CAST(NULL AS string) AS intrastat_division,
  CAST(NULL AS string) AS tax_report_flag,
  CAST(NULL AS string) AS name_control,
  CAST(NULL AS string) AS last_filing_flag,
  CAST(NULL AS string) AS priority,
  CAST(NULL AS string) AS route,
  CAST(NULL AS string) AS load_sequence,
  CAST(NULL AS string) AS pick_by_date,
  CAST(NULL AS string) AS profile,
  CAST(NULL AS string) AS tac_in_city_flag,
  CAST(NULL AS string) AS non_sales_price_list,
  CAST(NULL AS string) AS business_relation,
  CAST(NULL AS string) AS alternate_um,
  CAST(NULL AS string) AS city_code
FROM cm_mstr cm