-- ============================================================
-- Query     : d_customer_transformation
-- Table Type: DIMENSION
-- Purpose   : Transform and load data into 'd_customer'
-- ============================================================
WITH
  _source AS (
SELECT
  concat('msd_qad_',lower(ad_mstr.ad_domain)) || ad_mstr.ad_addr AS cust_key,
  concat('msd_qad_',lower(ad_mstr.ad_domain)) || ad_mstr.ad_addr AS src_sys_cd,
  CAST(NULL AS STRING) AS cust_id,
  CAST(NULL AS STRING) AS cust_nm,
  CAST(NULL AS STRING) AS cust_nm_en,
  CAST(NULL AS STRING) AS cust_type_cd,
  CAST(NULL AS STRING) AS cust_type_nm,
  CAST(NULL AS STRING) AS active_flg,
  CAST(NULL AS STRING) AS parent_cust_id,
  CAST(NULL AS STRING) AS parent_cust_nm,
  CAST(NULL AS STRING) AS naics_cd,
  CAST(NULL AS STRING) AS naics_nm,
  CAST(NULL AS STRING) AS sic_cd,
  CAST(NULL AS STRING) AS sic_nm,
  CAST(NULL AS STRING) AS gbl_govt_id,
  CAST(NULL AS STRING) AS gbl_loc_nbr,
  CAST(NULL AS STRING) AS dnb_duns_nm,
  CAST(NULL AS STRING) AS alt_payer_cust_id,
  CAST(NULL AS STRING) AS annl_sls_amt,
  CAST(NULL AS STRING) AS central_bill_block_cd,
  CAST(NULL AS STRING) AS central_bill_block_nm,
  CAST(NULL AS STRING) AS central_delvr_block_cd,
  CAST(NULL AS STRING) AS central_delvr_block_nm,
  CAST(NULL AS STRING) AS central_ord_block_cd,
  CAST(NULL AS STRING) AS central_ord_block_nm,
  CAST(NULL AS STRING) AS cust_acct_grp_cd,
  CAST(NULL AS STRING) AS cust_acct_grp_nm,
  CAST(NULL AS STRING) AS cust_class_cd,
  CAST(NULL AS STRING) AS cust_class_nm,
  CAST(NULL AS STRING) AS curncy_cd,
  CAST(NULL AS STRING) AS curncy_nm,
  CAST(NULL AS STRING) AS indy_cd,
  CAST(NULL AS STRING) AS indy_nm,
  CAST(NULL AS STRING) AS intl_loc_nbr_check_digit,
  CAST(NULL AS STRING) AS lang_cd,
  CAST(NULL AS STRING) AS lang_iso_cd,
  CAST(NULL AS STRING) AS lang_nm,
  CAST(NULL AS STRING) AS lgl_stat_cd,
  CAST(NULL AS STRING) AS lgl_stat_nm,
  CAST(NULL AS STRING) AS rgn_mkt,
  CAST(NULL AS STRING) AS sls_since_yr,
  CAST(NULL AS STRING) AS sort_field,
  CAST(NULL AS STRING) AS tax_juris_cd,
  CAST(NULL AS STRING) AS tax_juris_nm,
  CAST(NULL AS STRING) AS teletex_nbr,
  CAST(NULL AS STRING) AS telex_nbr,
  CAST(NULL AS STRING) AS title,
  CAST(NULL AS STRING) AS transp_zone_cd,
  CAST(NULL AS STRING) AS transp_zone_nm,
  CAST(NULL AS STRING) AS trading_prtnr_co_cd,
  CAST(NULL AS STRING) AS url,
  CAST(NULL AS STRING) AS unload_point_flg,
  CAST(NULL AS STRING) AS vat_regstr_nbr,
  CAST(NULL AS STRING) AS central_del_block_flg,
  CAST(NULL AS STRING) AS central_del_flg,
  CAST(NULL AS STRING) AS central_post_block_flg,
  CAST(NULL AS STRING) AS central_sls_block_flg,
  CAST(NULL AS STRING) AS cmptr_flg,
  CAST(NULL AS STRING) AS natural_pers_flg,
  CAST(NULL AS STRING) AS one_time_cust_flg,
  CAST(NULL AS STRING) AS sls_prtnr_flg,
  CAST(NULL AS STRING) AS sls_prospect_flg,
  CAST(NULL AS STRING) AS addr_key,
  CAST(NULL AS STRING) AS street_line,
  CAST(NULL AS STRING) AS pstl_cd,
  CAST(NULL AS STRING) AS city,
  CAST(NULL AS STRING) AS city_coord,
  CAST(NULL AS STRING) AS po_box,
  CAST(NULL AS STRING) AS po_box_pstl_cd,
  CAST(NULL AS STRING) AS district,
  CAST(NULL AS STRING) AS st_prov_cd,
  CAST(NULL AS STRING) AS st_prov_nm,
  ad_ctry AS cntry_cd,
  CAST(NULL AS STRING) AS cntry_nm,
  CAST(NULL AS STRING) AS fax_nbr,
  CAST(NULL AS STRING) AS trading_prtnr_co_nm,
  CAST(NULL AS STRING) AS prim_contact_key,
  CAST(NULL AS STRING) AS dnb_duns_nbr,
  CAST(NULL AS STRING) AS addr_nm_line2,
  CAST(NULL AS STRING) AS addr_nm_line3,
  addr_nm_line4,
  cust_cond_grp_cd1,
  cust_cond_grp_cd2,
  cust_cond_grp_nm1,
  cust_cond_grp_nm2,
  cust_email_addr_txt,
  cust_rept_hier_base,
  dw_src_key,
  indy_cd1,
  indy_cd2,
  indy_nm1,
  indy_nm2,
  intl_loc_nbr1,
  intl_loc_nbr2,
  phn_nbr1,
  phn_nbr2,
  search_mcode1,
  search_mcode2,
  search_mcode3,
  sply_center_cd,
  sply_center_flg,
  sply_center_nm,
  tax_nbr1,
  tax_nbr2,
  tax_nbr3,
  src_crt_by,
  src_crt_ts,
  src_updt_by,
  cm_mod_date AS src_updt_ts,
  CAST(NULL AS TIMESTAMP) AS rec_crt_ts,
  CAST(NULL AS TIMESTAMP) AS rec_updt_ts,
  CAST(NULL AS STRING) AS stock_ticker_cd,
  CAST(NULL AS STRING) AS cdw_cust_key,
  CAST(NULL AS STRING) AS dw_cust_key,
  CAST(NULL AS STRING) AS addr_phn_nbr,
  addr_fax_nbr,
  CAST(NULL AS STRING) AS sls_chnl_cd,
  CAST(NULL AS STRING) AS sls_terr_cd,
  CAST(NULL AS STRING) AS sls_rep_cust_key,
  CAST(NULL AS STRING) AS addr_type_cd,
  CAST(NULL AS STRING) AS hfm_entity_key,
  CAST(NULL AS STRING) AS hfm_entity_cd,
  cntry_hier_key AS deflt_delvr_cntry_key,
  deflt_delvr_cntry_cd,
  CAST(NULL AS STRING) AS trade_chnl_cd,
  CASE WHEN ad_mstr.ad_addr LIKE 'Z%' OR ad_mstr.ad_addr LIKE 'TM%' THEN 'IC'
       ELSE '3rd'
  END AS inter_co_cd
FROM <source>
WHERE 1=1
  ),
  _scd AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY cust_key ORDER BY CURRENT_TIMESTAMP DESC) AS _rn
    FROM   _source
  ),
  _transformed AS (
    SELECT cust_key,
           src_sys_cd,
           cust_id,
           cust_nm,
           cust_nm_en,
           cust_type_cd,
           cust_type_nm,
           active_flg,
           parent_cust_id,
           parent_cust_nm,
           naics_cd,
           naics_nm,
           sic_cd,
           sic_nm,
           gbl_govt_id,
           gbl_loc_nbr,
           dnb_duns_nm,
           alt_payer_cust_id,
           annl_sls_amt,
           central_bill_block_cd,
           central_bill_block_nm,
           central_delvr_block_cd,
           central_delvr_block_nm,
           central_ord_block_cd,
           central_ord_block_nm,
           cust_acct_grp_cd,
           cust_acct_grp_nm,
           cust_class_cd,
           cust_class_nm,
           curncy_cd,
           curncy_nm,
           indy_cd,
           indy_nm,
           intl_loc_nbr_check_digit,
           lang_cd,
           lang_iso_cd,
           lang_nm,
           lgl_stat_cd,
           lgl_stat_nm,
           rgn_mkt,
           sls_since_yr,
           sort_field,
           tax_juris_cd,
           tax_juris_nm,
           teletex_nbr,
           telex_nbr,
           title,
           transp_zone_cd,
           transp_zone_nm,
           trading_prtnr_co_cd,
           url,
           unload_point_flg,
           vat_regstr_nbr,
           central_del_block_flg,
           central_del_flg,
           central_post_block_flg,
           central_sls_block_flg,
           cmptr_flg,
           natural_pers_flg,
           one_time_cust_flg,
           sls_prtnr_flg,
           sls_prospect_flg,
           addr_key,
           street_line,
           pstl_cd,
           city,
           city_coord,
           po_box,
           po_box_pstl_cd,
           district,
           st_prov_cd,
           st_prov_nm,
           cntry_cd,
           cntry_nm,
           fax_nbr,
           trading_prtnr_co_nm,
           prim_contact_key,
           dnb_duns_nbr,
           addr_nm_line2,
           addr_nm_line3,
           addr_nm_line4,
           cust_cond_grp_cd1,
           cust_cond_grp_cd2,
           cust_cond_grp_nm1,
           cust_cond_grp_nm2,
           cust_email_addr_txt,
           cust_rept_hier_base,
           dw_src_key,
           indy_cd1,
           indy_cd2,
           indy_nm1,
           indy_nm2,
           intl_loc_nbr1,
           intl_loc_nbr2,
           phn_nbr1,
           phn_nbr2,
           search_mcode1,
           search_mcode2,
           search_mcode3,
           sply_center_cd,
           sply_center_flg,
           sply_center_nm,
           tax_nbr1,
           tax_nbr2,
           tax_nbr3,
           src_crt_by,
           src_crt_ts,
           src_updt_by,
           src_updt_ts,
           rec_crt_ts,
           rec_updt_ts,
           stock_ticker_cd,
           cdw_cust_key,
           dw_cust_key,
           addr_phn_nbr,
           addr_fax_nbr,
           sls_chnl_cd,
           sls_terr_cd,
           sls_rep_cust_key,
           addr_type_cd,
           hfm_entity_key,
           hfm_entity_cd,
           deflt_delvr_cntry_key,
           deflt_delvr_cntry_cd,
           trade_chnl_cd,
           inter_co_cd
    FROM   _scd
    WHERE  _rn = 1
  )
SELECT * FROM _transformed;