-- Query: d_product_transformation
-- Purpose: Transform and load data into d_product
-- Query Type: SELECT

-- Query: d_product_transformation
-- Purpose: Transform and load data into 'd_product'
-- Query Type: SELECT

WITH
  _source_d_product_1 AS (
SELECT
  CAST(NULL AS STRING) AS purch_val_cd,
  CAST(NULL AS STRING) AS purch_val_nm,
  CAST(NULL AS STRING) AS rd_proj_cd,
  CAST(NULL AS STRING) AS rd_proj_nm,
  CAST(NULL AS STRING) AS rev_lvl_assgn_flg,
  CAST(NULL AS INT) AS sell_days,
  CAST(NULL AS INT) AS sheets_cnt,
  CAST(NULL AS STRING) AS ship_cond_cd,
  CAST(NULL AS STRING) AS ship_cond_nm,
  CAST(NULL AS TIMESTAMP) AS sku_launch_dt,
  CAST(NULL AS STRING) AS sku_size,
  CAST(NULL AS STRING) AS sku_sub_type_cd,
  CAST(NULL AS STRING) AS sku_sup_type_nm,
  CAST(NULL AS STRING) AS sku_type_cd,
  CAST(NULL AS STRING) AS sku_type_nm,
  CAST(NULL AS STRING) AS src_div_cd,
  'byd_brsbn' AS src_sys_cd,
  CAST(NULL AS INT) AS src_sys_prod_id,
  CAST(NULL AS STRING) AS stk_type_cd,
  CAST(NULL AS STRING) AS stk_type_nm,
  CAST(NULL AS STRING) AS strg_cond_cd,
  CAST(NULL AS STRING) AS strg_cond_nm,
  CAST(NULL AS STRING) AS sub_prod_line_cd,
  CAST(NULL AS STRING) AS sub_prod_line_nm,
  CAST(NULL AS STRING) AS temp_cond_cd,
  CAST(NULL AS STRING) AS temp_cond_nm,
  CAST(NULL AS STRING) AS transp_grp_cd,
  CAST(NULL AS STRING) AS transp_grp_nm,
  CAST(NULL AS DECIMAL(20,0)) AS ttl_shelf_life_days,
  CAST(NULL AS STRING) AS unspsc,
  CAST(NULL AS STRING) AS x_distrb_chain_mtl_stat_cd,
  CAST(NULL AS TIMESTAMP) AS x_distrb_chain_mtl_stat_dt,
  CAST(NULL AS STRING) AS x_distrb_chain_mtl_stat_nm,
  CAST(NULL AS STRING) AS x_plant_config_flg,
  CAST(NULL AS STRING) AS x_plant_mtl_stat_cd,
  CAST(NULL AS TIMESTAMP) AS x_plant_mtl_stat_dt,
  CAST(NULL AS STRING) AS x_plant_mtl_stat_nm
FROM sap_dim_product_1
WHERE src_sys_cd IS NOT NULL AND sku IS NOT NULL
  ),
  _source_d_product_2 AS (
SELECT
  sap_dim_product_1.cbase_measure_unit_code AS base_uom_cd,
  sap_dim_product_1.tbase_measure_unit_code AS base_uom_nm,
  sap_dim_product_1.cs1ansda32b006df87a0b AS cas_reg_nbr,
  sap_dim_product_1.KCGROSS_WEIGHT AS gross_wgt,
  sap_dim_product_1.KCHEIGHT AS height,
  sap_dim_product_1.CPROD_CATG_UUID_01 AS item_cat_grp_cd,
  sap_dim_product_1.TPROD_CATG_UUID_01 AS item_cat_grp_nm,
  sap_dim_product_1.KCLENGTH AS length,
  sap_dim_product_1.Cs1ANsD0A4BBEA40DDD66 AS mfr_part_nbr,
  sap_dim_product_1.CPROD_CATG_UUID_01 AS mtl_grp_cd,
  sap_dim_product_1.TPROD_CATG_UUID_01 AS mtl_grp_nm,
  sap_dim_product_1.Cs1ANs6BA9E26842229D1 AS mtl_type_cd,
  sap_dim_product_1.Ts1ANs6BA9E26842229D1 AS mtl_type_nm,
  sap_dim_product_1.KCNET_WEIGHT AS net_wgt,
  sap_dim_product_1.CMATR_INT_ID AS sku,
  sap_dim_product_1.TMATR_INT_ID AS sku_nm,
  sap_dim_product_1.KCGROSS_VOLUME AS vol,
  sap_dim_product_1.CGROSS_VOLUME_UNIT_CODE AS vol_uom_cd,
  sap_dim_product_1.TGROSS_VOLUME_UNIT_CODE AS vol_uom_nm,
  sap_dim_product_1.CGROSS_WEIGHT_UNIT_CODE AS wgt_uom_cd,
  sap_dim_product_1.TGROSS_WEIGHT_UNIT_CODE AS wgt_uom_nm,
  sap_dim_product_1.KCWIDTH AS width,
  CAST(NULL AS string) AS adj_unit_mult_nbr,
  CAST(NULL AS string) AS alt_sku,
  CAST(NULL AS string) AS alt_uom_cd,
  CAST(NULL AS string) AS alt_uom_nm,
  CAST(NULL AS string) AS auth_grp,
  CAST(NULL AS string) AS batch_mgmt_flg,
  CAST(NULL AS string) AS bus_area_cd,
  CAST(NULL AS string) AS bus_area_nm
FROM sap_dim_product_1
WHERE sap_dim_product_1.CMATR_INT_ID IS NOT NULL AND sap_dim_product_1.src_sys_cd IS NOT NULL
  ),
  _transformed AS (
  SELECT
    purch_val_cd AS purch_val_cd,
    purch_val_nm AS purch_val_nm,
    rd_proj_cd AS rd_proj_cd,
    rd_proj_nm AS rd_proj_nm,
    rev_lvl_assgn_flg AS rev_lvl_assgn_flg,
    sell_days AS sell_days,
    sheets_cnt AS sheets_cnt,
    ship_cond_cd AS ship_cond_cd,
    ship_cond_nm AS ship_cond_nm,
    sku_launch_dt AS sku_launch_dt,
    sku_size AS sku_size,
    sku_sub_type_cd AS sku_sub_type_cd,
    sku_sup_type_nm AS sku_sup_type_nm,
    sku_type_cd AS sku_type_cd,
    sku_type_nm AS sku_type_nm,
    src_div_cd AS src_div_cd,
    src_sys_cd AS src_sys_cd,
    src_sys_prod_id AS src_sys_prod_id,
    stk_type_cd AS stk_type_cd,
    stk_type_nm AS stk_type_nm,
    strg_cond_cd AS strg_cond_cd,
    strg_cond_nm AS strg_cond_nm,
    sub_prod_line_cd AS sub_prod_line_cd,
    sub_prod_line_nm AS sub_prod_line_nm,
    temp_cond_cd AS temp_cond_cd,
    temp_cond_nm AS temp_cond_nm,
    transp_grp_cd AS transp_grp_cd,
    transp_grp_nm AS transp_grp_nm,
    ttl_shelf_life_days AS ttl_shelf_life_days,
    unspsc AS unspsc,
    x_distrb_chain_mtl_stat_cd AS x_distrb_chain_mtl_stat_cd,
    x_distrb_chain_mtl_stat_dt AS x_distrb_chain_mtl_stat_dt,
    x_distrb_chain_mtl_stat_nm AS x_distrb_chain_mtl_stat_nm,
    x_plant_config_flg AS x_plant_config_flg,
    x_plant_mtl_stat_cd AS x_plant_mtl_stat_cd,
    x_plant_mtl_stat_dt AS x_plant_mtl_stat_dt,
    x_plant_mtl_stat_nm AS x_plant_mtl_stat_nm,
    base_uom_cd AS base_uom_cd,
    base_uom_nm AS base_uom_nm,
    cas_reg_nbr AS cas_reg_nbr,
    gross_wgt AS gross_wgt,
    height AS height,
    item_cat_grp_cd AS item_cat_grp_cd,
    item_cat_grp_nm AS item_cat_grp_nm,
    length AS length,
    mfr_part_nbr AS mfr_part_nbr,
    mtl_grp_cd AS mtl_grp_cd,
    mtl_grp_nm AS mtl_grp_nm,
    mtl_type_cd AS mtl_type_cd,
    mtl_type_nm AS mtl_type_nm,
    net_wgt AS net_wgt,
    sku AS sku,
    sku_nm AS sku_nm,
    vol AS vol,
    vol_uom_cd AS vol_uom_cd,
    vol_uom_nm AS vol_uom_nm,
    wgt_uom_cd AS wgt_uom_cd,
    wgt_uom_nm AS wgt_uom_nm,
    width AS width,
    adj_unit_mult_nbr AS adj_unit_mult_nbr,
    alt_sku AS alt_sku,
    alt_uom_cd AS alt_uom_cd,
    alt_uom_nm AS alt_uom_nm,
    auth_grp AS auth_grp,
    batch_mgmt_flg AS batch_mgmt_flg,
    bus_area_cd AS bus_area_cd,
    bus_area_nm AS bus_area_nm
  FROM _source_d_product_2
  )
SELECT * FROM _transformed;