-- Databricks notebook source
-- Generated for: SCRUM-62
-- Universal Plan Schema generation
--
-- Query 1: d_customer_transformation
--   Pattern: dimension_flat

/**************************************************************************
Generated plan for d_customer dimension table.
**************************************************************************/

-- Query: d_customer_transformation
-- Pattern: dimension_flat
-- Coverage: 168 rows
-- WARNING: unresolved items: No source_table or source_field provided for any field.; No source_table or source_field provided for any field. All expressions defaulted to CAST(NULL AS string).

SELECT
  CAST(NULL AS string) AS src_sys_cd,
  CAST(NULL AS string) AS cust_id,
  CAST(NULL AS string) AS cust_nm,
  CAST(NULL AS string) AS cust_nm_en,
  CAST(NULL AS string) AS cust_type_cd,
  CAST(NULL AS string) AS cust_type_nm,
  CAST(NULL AS string) AS active_flg,
  CAST(NULL AS string) AS parent_cust_id,
  CAST(NULL AS string) AS parent_cust_nm,
  CAST(NULL AS string) AS naics_cd,
  CAST(NULL AS string) AS naics_nm,
  CAST(NULL AS string) AS sic_cd,
  CAST(NULL AS string) AS sic_nm,
  CAST(NULL AS string) AS gbl_govt_id,
  CAST(NULL AS string) AS gbl_loc_nbr,
  CAST(NULL AS string) AS dnb_duns_nm,
  CAST(NULL AS string) AS alt_payer_cust_id,
  CAST(NULL AS string) AS annl_sls_amt,
  CAST(NULL AS string) AS central_bill_block_cd,
  CAST(NULL AS string) AS central_bill_block_nm,
  CAST(NULL AS string) AS central_delvr_block_cd,
  CAST(NULL AS string) AS central_delvr_block_nm,
  CAST(NULL AS string) AS central_ord_block_cd,
  CAST(NULL AS string) AS central_ord_block_nm,
  CAST(NULL AS string) AS cust_acct_grp_cd,
  CAST(NULL AS string) AS cust_acct_grp_nm,
  CAST(NULL AS string) AS cust_class_cd,
  CAST(NULL AS string) AS cust_class_nm,
  CAST(NULL AS string) AS curncy_cd,
  CAST(NULL AS string) AS curncy_nm,
  CAST(NULL AS string) AS indy_cd,
  CAST(NULL AS string) AS indy_nm,
  CAST(NULL AS string) AS intl_loc_nbr_check_digit,
  CAST(NULL AS string) AS lang_cd,
  CAST(NULL AS string) AS lang_iso_cd,
  CAST(NULL AS string) AS lang_nm,
  CAST(NULL AS string) AS lgl_stat_cd,
  CAST(NULL AS string) AS lgl_stat_nm,
  CAST(NULL AS string) AS rgn_mkt,
  CAST(NULL AS string) AS sls_since_yr,
  CAST(NULL AS string) AS sort_field,
  CAST(NULL AS string) AS tax_juris_cd,
  CAST(NULL AS string) AS tax_juris_nm,
  CAST(NULL AS string) AS teletex_nbr,
  CAST(NULL AS string) AS telex_nbr,
  CAST(NULL AS string) AS title,
  CAST(NULL AS string) AS transp_zone_cd,
  CAST(NULL AS string) AS transp_zone_nm,
  CAST(NULL AS string) AS trading_prtnr_co_cd,
  CAST(NULL AS string) AS url,
  CAST(NULL AS string) AS unload_point_flg,
  CAST(NULL AS string) AS vat_regstr_nbr,
  CAST(NULL AS string) AS central_del_block_flg,
  CAST(NULL AS string) AS central_del_flg,
  CAST(NULL AS string) AS central_post_block_flg,
  CAST(NULL AS string) AS central_sls_block_flg,
  CAST(NULL AS string) AS cmptr_flg,
  CAST(NULL AS string) AS natural_pers_flg,
  CAST(NULL AS string) AS one_time_cust_flg,
  CAST(NULL AS string) AS sls_prtnr_flg,
  CAST(NULL AS string) AS sls_prospect_flg,
  CAST(NULL AS string) AS addr_key,
  CAST(NULL AS string) AS street_line,
  CAST(NULL AS string) AS pstl_cd,
  CAST(NULL AS string) AS city,
  CAST(NULL AS string) AS city_coord,
  CAST(NULL AS string) AS po_box,
  CAST(NULL AS string) AS po_box_pstl_cd,
  CAST(NULL AS string) AS district,
  CAST(NULL AS string) AS st_prov_cd,
  CAST(NULL AS string) AS st_prov_nm,
  CAST(NULL AS string) AS cntry_cd,
  CAST(NULL AS string) AS cntry_nm,
  CAST(NULL AS string) AS fax_nbr,
  CAST(NULL AS string) AS trading_prtnr_co_nm,
  CAST(NULL AS string) AS prim_contact_key,
  CAST(NULL AS string) AS dnb_duns_nbr,
  CAST(NULL AS string) AS addr_nm_line2,
  CAST(NULL AS string) AS addr_nm_line3,
  CAST(NULL AS string) AS addr_nm_line4,
  CAST(NULL AS string) AS cust_cond_grp_cd1,
  CAST(NULL AS string) AS cust_cond_grp_cd2,
  CAST(NULL AS string) AS cust_cond_grp_nm1,
  CAST(NULL AS string) AS cust_cond_grp_nm2,
  CAST(NULL AS string) AS cust_email_addr_txt,
  CAST(NULL AS string) AS cust_rept_hier_base,
  CAST(NULL AS string) AS dw_src_key,
  CAST(NULL AS string) AS indy_cd1,
  CAST(NULL AS string) AS indy_cd2,
  CAST(NULL AS string) AS indy_nm1,
  CAST(NULL AS string) AS indy_nm2,
  CAST(NULL AS string) AS intl_loc_nbr1,
  CAST(NULL AS string) AS intl_loc_nbr2,
  CAST(NULL AS string) AS phn_nbr1,
  CAST(NULL AS string) AS phn_nbr2,
  CAST(NULL AS string) AS search_mcode1,
  CAST(NULL AS string) AS search_mcode2,
  CAST(NULL AS string) AS search_mcode3,
  CAST(NULL AS string) AS sply_center_cd,
  CAST(NULL AS string) AS sply_center_flg,
  CAST(NULL AS string) AS sply_center_nm,
  CAST(NULL AS string) AS tax_nbr1,
  CAST(NULL AS string) AS tax_nbr2,
  CAST(NULL AS string) AS tax_nbr3,
  CAST(NULL AS string) AS src_crt_by,
  CAST(NULL AS string) AS src_crt_ts,
  CAST(NULL AS string) AS src_updt_by,
  CAST(NULL AS string) AS src_updt_ts,
  CAST(NULL AS string) AS rec_crt_ts,
  CAST(NULL AS string) AS rec_updt_ts,
  CAST(NULL AS string) AS stock_ticker_cd,
  CAST(NULL AS string) AS cdw_cust_key,
  CAST(NULL AS string) AS dw_cust_key,
  CAST(NULL AS string) AS addr_phn_nbr,
  CAST(NULL AS string) AS addr_fax_nbr,
  CAST(NULL AS string) AS sls_chnl_cd,
  CAST(NULL AS string) AS sls_terr_cd,
  CAST(NULL AS string) AS sls_rep_cust_key,
  CAST(NULL AS string) AS addr_type_cd,
  CAST(NULL AS string) AS hfm_entity_key,
  CAST(NULL AS string) AS hfm_entity_cd,
  CAST(NULL AS string) AS deflt_delvr_cntry_key,
  CAST(NULL AS string) AS deflt_delvr_cntry_cd,
  CAST(NULL AS string) AS trade_chnl_cd,
  CAST(NULL AS string) AS inter_co_cd,
  CAST(NULL AS string) AS county,
  CAST(NULL AS string) AS temporary flag,
  CAST(NULL AS string) AS Bank Acct 1,
  CAST(NULL AS string) AS CoC Number,
  CAST(NULL AS string) AS Tax ID - Federal,
  CAST(NULL AS string) AS Tax Type,
  CAST(NULL AS string) AS Tax Class Code,
  CAST(NULL AS string) AS taxable flag,
  CAST(NULL AS string) AS tax in flag,
  CAST(NULL AS string) AS Netting Logic,
  CAST(NULL AS string) AS Trading Prtnr Interface ID,
  CAST(NULL AS string) AS EDI Control,
  CAST(NULL AS string) AS Time Zone,
  CAST(NULL AS string) AS Trading Prtnr EDI ID,
  CAST(NULL AS string) AS Barcode Label Print Program,
  CAST(NULL AS string) AS Barcode Validation Program,
  CAST(NULL AS string) AS Calendar,
  CAST(NULL AS string) AS EDI Standard,
  CAST(NULL AS string) AS EDI Standard Level,
  CAST(NULL AS string) AS Trd Partner Location Code,
  CAST(NULL AS string) AS Tax Zone,
  CAST(NULL AS string) AS Tax ID - Misc 1,
  CAST(NULL AS string) AS Tax ID - Misc 2,
  CAST(NULL AS string) AS Tax ID - Misc 3,
  CAST(NULL AS string) AS Week Offset,
  CAST(NULL AS string) AS Invoices Via,
  CAST(NULL AS string) AS Schedules Via,
  CAST(NULL AS string) AS Purchase Orders Via,
  CAST(NULL AS string) AS ASN Default Data,
  CAST(NULL AS string) AS IntraStat Division,
  CAST(NULL AS string) AS Tax Report Flag,
  CAST(NULL AS string) AS Name Control,
  CAST(NULL AS string) AS Last Filing Flag,
  CAST(NULL AS string) AS Priority,
  CAST(NULL AS string) AS Route,
  CAST(NULL AS string) AS Load Sequence,
  CAST(NULL AS string) AS Pick By Date,
  CAST(NULL AS string) AS Profile,
  CAST(NULL AS string) AS tac In City Flag,
  CAST(NULL AS string) AS Non-Sales Price List,
  CAST(NULL AS string) AS Business Relation,
  CAST(NULL AS string) AS Alternate UM,
  CAST(NULL AS string) AS City Code
FROM <source> src