-- Databricks notebook source
-- Generated for: SCRUM-62
-- Universal Plan Schema generation
--
-- Query 1: d_customer_transformation
--   Pattern: dimension_flat

/**************************************************************************
Generated plan for d_customer dimension table.
**************************************************************************/

-- Query: d_customer_transformation
-- Pattern: dimension_flat
-- Coverage: 168 rows
-- WARNING: unresolved items: No source_table or source_field provided for any row. All expressions defaulted to CAST(NULL AS string).

SELECT
  src.Source System Code AS src_sys_cd,
  src.Customer ID AS cust_id,
  src.Customer Name AS cust_nm,
  src.Customer Name English AS cust_nm_en,
  src.Customer Type Code AS cust_type_cd,
  src.Customer Type Name AS cust_type_nm,
  src.Active Flag AS active_flg,
  src.Parent Customer ID AS parent_cust_id,
  src.Parent Customer Name AS parent_cust_nm,
  src.Naics Code AS naics_cd,
  src.Naics Name AS naics_nm,
  src.Sic Code AS sic_cd,
  src.Sic Name AS sic_nm,
  src.Global Government ID AS gbl_govt_id,
  src.Global Location Number AS gbl_loc_nbr,
  src.Dnb Duns Name AS dnb_duns_nm,
  src.Alternative Payer Customer Identifier AS alt_payer_cust_id,
  src.Annual Sales Amount AS annl_sls_amt,
  src.Central Billing Block Code AS central_bill_block_cd,
  src.Central Billing Block Name AS central_bill_block_nm,
  src.Central Delivery Block Code AS central_delvr_block_cd,
  src.Central Delivery Block Name AS central_delvr_block_nm,
  src.Central Order Block Code AS central_ord_block_cd,
  src.Central Order Block Name AS central_ord_block_nm,
  src.Customer Account Group Code AS cust_acct_grp_cd,
  src.Customer Account Group Name AS cust_acct_grp_nm,
  src.Customer Classification Code AS cust_class_cd,
  src.Customer Classification Name AS cust_class_nm,
  src.Currency Code AS curncy_cd,
  src.Currency Name AS curncy_nm,
  src.Industry Code AS indy_cd,
  src.Industry Name AS indy_nm,
  CAST(NULL AS STRING) AS intl_loc_nbr_check_digit,
  src.Language Code AS lang_cd,
  src.Language Iso Code AS lang_iso_cd,
  src.Language Name AS lang_nm,
  src.Legal Status Code AS lgl_stat_cd,
  src.Legal Status Name AS lgl_stat_nm,
  src.Regional Market AS rgn_mkt,
  src.Sales Since Year AS sls_since_yr,
  src.Sort Field AS sort_field,
  src.Taxable Jurisdiction Code AS tax_juris_cd,
  src.Taxable Jurisdiction Name AS tax_juris_nm,
  src.Teletex Number AS teletex_nbr,
  src.Telex Number AS telex_nbr,
  src.Title AS title,
  src.Transportation Zone Code AS transp_zone_cd,
  src.Transportation Zone Name AS transp_zone_nm,
  src.Trading Partner Company Code AS trading_prtnr_co_cd,
  src.Url AS url,
  src.Unload Point Flag AS unload_point_flg,
  src.Vat Registration Number AS vat_regstr_nbr,
  src.Central Deletion Block Flag AS central_del_block_flg,
  src.Central Deletion Flag AS central_del_flg,
  src.Central Posting Block Flag AS central_post_block_flg,
  src.Central Sales Block Flag AS central_sls_block_flg,
  src.Competitor Flag AS cmptr_flg,
  src.Natural Person Flag AS natural_pers_flg,
  src.One Time Customer Flag AS one_time_cust_flg,
  src.Sales Partner Flag AS sls_prtnr_flg,
  src.Sales Prospect Flag AS sls_prospect_flg,
  src.Address Key AS addr_key,
  src.Street Line AS street_line,
  src.Postal Code AS pstl_cd,
  src.City AS city,
  src.City Coordinate AS city_coord,
  src.Purchase Order Box AS po_box,
  CAST(NULL AS STRING) AS po_box_pstl_cd,
  src.District AS district,
  src.State Province Code AS st_prov_cd,
  src.State Province Name AS st_prov_nm,
  src.Country Code AS cntry_cd,
  src.Country Name AS cntry_nm,
  src.Facsimile Number AS fax_nbr,
  src.Trading Partner Company Name AS trading_prtnr_co_nm,
  src.Primary Contact Key AS prim_contact_key,
  src.DNB Duns Number AS dnb_duns_nbr,
  src.Address Name Line2 AS addr_nm_line2,
  src.Address Name Line3 AS addr_nm_line3,
  src.Address Name Line4 AS addr_nm_line4,
  src.Customer Condition Grouping Cd1 AS cust_cond_grp_cd1,
  src.Customer Condition Grouping Cd2 AS cust_cond_grp_cd2,
  src.Customer Condition Grouping Nm1 AS cust_cond_grp_nm1,
  src.Customer Condition Grouping Nm2 AS cust_cond_grp_nm2,
  src.Customer Email Address Text AS cust_email_addr_txt,
  src.Customer Reports Hierarchy Base AS cust_rept_hier_base,
  src.Dw Source Key AS dw_src_key,
  src.Industry Cd1 AS indy_cd1,
  src.Industry Cd2 AS indy_cd2,
  src.Industry Nm1 AS indy_nm1,
  src.Industry Nm2 AS indy_nm2,
  src.International Location Nbr1 AS intl_loc_nbr1,
  src.International Location Nbr2 AS intl_loc_nbr2,
  src.Telephone Nbr1 AS phn_nbr1,
  src.Telephone Nbr2 AS phn_nbr2,
  src.Search Mcode1 AS search_mcode1,
  src.Search Mcode2 AS search_mcode2,
  src.Search Mcode3 AS search_mcode3,
  src.Sply Center Code AS sply_center_cd,
  src.Sply Center Flag AS sply_center_flg,
  src.Sply Center Name AS sply_center_nm,
  src.Taxable Nbr1 AS tax_nbr1,
  src.Taxable Nbr2 AS tax_nbr2,
  src.Taxable Nbr3 AS tax_nbr3,
  src.Source Create By AS src_crt_by,
  src.Source Create Timestamp AS src_crt_ts,
  src.Source Update By AS src_updt_by,
  src.Source Update Timestamp AS src_updt_ts,
  src.Record Create Timestamp AS rec_crt_ts,
  src.Record Update Timestamp AS rec_updt_ts,
  src.Stock Ticker Code AS stock_ticker_cd,
  src.CDW Customer Key AS cdw_cust_key,
  src.DW Customer Key AS dw_cust_key,
  src.Address Telephone Number AS addr_phn_nbr,
  src.Address Facsimile Number AS addr_fax_nbr,
  src.Sales Channel Code AS sls_chnl_cd,
  src.Sales Territory Code AS sls_terr_cd,
  src.Sales Representative Customer Key AS sls_rep_cust_key,
  src.Address Type Code AS addr_type_cd,
  src.HFM Entity Key AS hfm_entity_key,
  CAST(NULL AS string) AS hfm_entity_cd,
  CAST(NULL AS string) AS deflt_delvr_cntry_key,
  CAST(NULL AS string) AS deflt_delvr_cntry_cd,
  CAST(NULL AS string) AS trade_chnl_cd,
  CAST(NULL AS string) AS inter_co_cd,
  CAST(NULL AS string) AS county,
  CAST(NULL AS string) AS temporary_flag,
  CAST(NULL AS string) AS bank_acct_1,
  CAST(NULL AS string) AS coc_number,
  CAST(NULL AS string) AS tax_id_federal,
  CAST(NULL AS string) AS tax_type,
  CAST(NULL AS string) AS tax_class_code,
  CAST(NULL AS string) AS taxable_flag,
  CAST(NULL AS string) AS tax_in_flag,
  CAST(NULL AS string) AS netting_logic,
  CAST(NULL AS string) AS trading_prtnr_interface_id,
  CAST(NULL AS string) AS edi_control,
  CAST(NULL AS string) AS time_zone,
  CAST(NULL AS string) AS trading_prtnr_edi_id,
  CAST(NULL AS string) AS barcode_label_print_program,
  CAST(NULL AS string) AS barcode_validation_program,
  CAST(NULL AS string) AS calendar,
  CAST(NULL AS string) AS edi_standard,
  CAST(NULL AS string) AS edi_standard_level,
  CAST(NULL AS string) AS trd_partner_location_code,
  CAST(NULL AS string) AS tax_zone,
  CAST(NULL AS string) AS tax_id_misc_1,
  CAST(NULL AS string) AS tax_id_misc_2,
  CAST(NULL AS string) AS tax_id_misc_3,
  CAST(NULL AS string) AS week_offset,
  CAST(NULL AS string) AS invoices_via,
  CAST(NULL AS string) AS schedules_via,
  CAST(NULL AS string) AS purchase_orders_via,
  CAST(NULL AS string) AS asn_default_data,
  CAST(NULL AS string) AS intrastat_division,
  CAST(NULL AS string) AS tax_report_flag,
  CAST(NULL AS string) AS name_control,
  CAST(NULL AS string) AS last_filing_flag,
  CAST(NULL AS string) AS priority,
  CAST(NULL AS string) AS route,
  CAST(NULL AS string) AS load_sequence,
  CAST(NULL AS string) AS pick_by_date,
  CAST(NULL AS string) AS profile,
  CAST(NULL AS string) AS tac_in_city_flag,
  CAST(NULL AS string) AS non_sales_price_list,
  CAST(NULL AS string) AS business_relation,
  CAST(NULL AS string) AS alternate_um,
  CAST(NULL AS string) AS city_code
FROM src src