-- Query: dim_customer_transformation
-- Purpose: Transform and load data into the d_customer dimension table from source tables with necessary joins, transformations, and mappings.
-- Query Type: SELECT

WITH base_data AS (
    SELECT
        ad_mstr.ad_domain,
        ad_mstr.ad_addr,
        cm_mstr.cm_addr,
        ad_mstr.ad_name,
        ad_mstr.ad_type,
        cm_mstr.cm_curr,
        ad_mstr.ad_address_id,
        ad_mstr.ad_line2,
        ad_mstr.ad_zip,
        ad_mstr.ad_city,
        ad_mstr.ad_state,
        ad_mstr.ad_ctry,
        ad_mstr.ad_country,
        ad_mstr.ad_fax,
        ad_mstr.ad_line1,
        ad_mstr.ad_line2 AS addr_nm_line2,
        ad_mstr.ad_line3 AS addr_nm_line3,
        ad_mstr.ad_phone,
        cm_mstr.cm_mod_date,
        ad_mstr.ad_type AS cust_type_cd,
        currency.currencydescription AS curncy_nm,
        d_cntry_hier.cntry_hier_key
    FROM tfsdl_aig_qad_delta.cm_mstr AS cm_mstr
    LEFT JOIN tfsdl_aig_qad_delta.ad_mstr AS ad_mstr
        ON cm_mstr.cm_addr = ad_mstr.ad_addr
        AND LOWER(cm_mstr.cm_domain) = LOWER(ad_mstr.ad_domain)
    LEFT JOIN tfsdl_aig_qad_delta.currency AS currency
        ON currency.currencycode = cm_mstr.cm_curr
    JOIN tfsdl_edp_common_dims.d_cntry_hier AS d_cntry_hier
        ON UPPER(d_cntry_hier.cntry_nm) = ad_mstr.ad_country
),
transformed_data AS (
    SELECT
        CONCAT('msd_qad_', LOWER(ad_domain), '|', ad_addr) AS cust_key,
        CONCAT('msd_qad_', LOWER(ad_domain)) AS src_sys_cd,
        cm_addr AS cust_id,
        ad_name AS cust_nm,
        ad_name AS cust_nm_en,
        ad_type AS cust_type_cd,
        ad_type AS cust_type_nm,
        CAST(NULL AS STRING) AS active_flg,
        CAST(NULL AS STRING) AS parent_cust_id,
        CAST(NULL AS STRING) AS parent_cust_nm,
        CAST(NULL AS STRING) AS naics_cd,
        CAST(NULL AS STRING) AS naics_nm,
        CAST(NULL AS STRING) AS sic_cd,
        CAST(NULL AS STRING) AS sic_nm,
        CAST(NULL AS STRING) AS gbl_govt_id,
        CAST(NULL AS STRING) AS gbl_loc_nbr,
        CAST(NULL AS STRING) AS dnb_duns_nm,
        CAST(NULL AS STRING) AS alt_payer_cust_id,
        CAST(NULL AS STRING) AS annl_sls_amt,
        CAST(NULL AS STRING) AS central_bill_block_cd,
        CAST(NULL AS STRING) AS central_bill_block_nm,
        CAST(NULL AS STRING) AS central_delvr_block_cd,
        CAST(NULL AS STRING) AS central_delvr_block_nm,
        CAST(NULL AS STRING) AS central_ord_block_cd,
        CAST(NULL AS STRING) AS central_ord_block_nm,
        CAST(NULL AS STRING) AS cust_acct_grp_cd,
        CAST(NULL AS STRING) AS cust_acct_grp_nm,
        CAST(NULL AS STRING) AS cust_class_cd,
        CAST(NULL AS STRING) AS cust_class_nm,
        cm_curr AS curncy_cd,
        curncy_nm,
        CAST(NULL AS STRING) AS indy_cd,
        CAST(NULL AS STRING) AS indy_nm,
        CAST(NULL AS STRING) AS intl_loc_nbr_check_digit,
        ad_lang AS lang_cd,
        CAST(NULL AS STRING) AS lang_iso_cd,
        CAST(NULL AS STRING) AS lang_nm,
        CAST(NULL AS STRING) AS lgl_stat_cd,
        CAST(NULL AS STRING) AS lgl_stat_nm,
        CAST(NULL AS STRING) AS rgn_mkt,
        CAST(NULL AS STRING) AS sls_since_yr,
        ad_sort AS sort_field,
        ad_tax_usage AS tax_juris_cd,
        CAST(NULL AS STRING) AS tax_juris_nm,
        CAST(NULL AS STRING) AS teletex_nbr,
        CAST(NULL AS STRING) AS telex_nbr,
        CAST(NULL AS STRING) AS title,
        CAST(NULL AS STRING) AS transp_zone_cd,
        CAST(NULL AS STRING) AS transp_zone_nm,
        CAST(NULL AS STRING) AS trading_prtnr_co_cd,
        CAST(NULL AS STRING) AS url,
        CAST(NULL AS STRING) AS unload_point_flg,
        ad_vat_reg AS vat_regstr_nbr,
        CAST(NULL AS STRING) AS central_del_block_flg,
        CAST(NULL AS STRING) AS central_del_flg,
        CAST(NULL AS STRING) AS central_post_block_flg,
        CAST(NULL AS STRING) AS central_sls_block_flg,
        CAST(NULL AS STRING) AS cmptr_flg,
        CAST(NULL AS STRING) AS natural_pers_flg,
        CAST(NULL AS STRING) AS one_time_cust_flg,
        CAST(NULL AS STRING) AS sls_prtnr_flg,
        CAST(NULL AS STRING) AS sls_prospect_flg,
        CONCAT('msd_qad_', LOWER(ad_domain), '|', ad_address_id) AS addr_key,
        ad_line2 AS street_line,
        ad_zip AS pstl_cd,
        ad_city AS city,
        CAST(NULL AS STRING) AS city_coord,
        CAST(NULL AS STRING) AS po_box,
        CAST(NULL AS STRING) AS po_box_pstl_cd,
        CAST(NULL AS STRING) AS district,
        ad_state AS st_prov_cd,
        CAST(NULL AS STRING) AS st_prov_nm,
        ad_ctry AS cntry_cd,
        ad_country AS cntry_nm,
        ad_fax AS fax_nbr,
        CAST(NULL AS STRING) AS trading_prtnr_co_nm,
        CAST(NULL AS STRING) AS prim_contact_key,
        CAST(NULL AS STRING) AS dnb_duns_nbr,
        addr_nm_line2,
        addr_nm_line3,
        ad_line3 AS addr_nm_line4,
        CAST(NULL AS STRING) AS cust_cond_grp_cd1,
        CAST(NULL AS STRING) AS cust_cond_grp_cd2,
        CAST(NULL AS STRING) AS cust_cond_grp_nm1,
        CAST(NULL AS STRING) AS cust_cond_grp_nm2,
        ad_email AS cust_email_addr_txt,
        CAST(NULL AS STRING) AS cust_rept_hier_base,
        CAST(NULL AS STRING) AS dw_src_key,
        CAST(NULL AS STRING) AS indy_cd1,
        CAST(NULL AS STRING) AS indy_cd2,
        CAST(NULL AS STRING) AS indy_nm1,
        CAST(NULL AS STRING) AS indy_nm2,
        CAST(NULL AS STRING) AS intl_loc_nbr1,
        CAST(NULL AS STRING) AS intl_loc_nbr2,
        ad_phone AS phn_nbr1,
        ad_phone2 AS phn_nbr2,
        CAST(NULL AS STRING) AS search_mcode1,
        CAST(NULL AS STRING) AS search_mcode2,
        CAST(NULL AS STRING) AS search_mcode3,
        CAST(NULL AS STRING) AS sply_center_cd,
        CAST(NULL AS STRING) AS sply_center_flg,
        CAST(NULL AS STRING) AS sply_center_nm,
        ad_pst_id AS tax_nbr1,
        CAST(NULL AS STRING) AS tax_nbr2,
        CAST(NULL AS STRING) AS tax_nbr3,
        CAST(NULL AS STRING) AS src_crt_by,
        CAST(ad_date AS STRING) AS src_crt_ts,
        ad_userid AS src_updt_by,
        SUBSTR(cm_mod_date, 1, 11) AS src_updt_ts,
        CURRENT_TIMESTAMP AS rec_crt_ts,
        CURRENT_TIMESTAMP AS rec_updt_ts,
        CAST(NULL AS STRING) AS stock_ticker_cd,
        CAST(NULL AS STRING) AS cdw_cust_key,
        CAST(NULL AS STRING) AS dw_cust_key,
        CAST(NULL AS STRING) AS addr_phn_nbr,
        ad_fax2 AS addr_fax_nbr,
        CAST(NULL AS STRING) AS sls_chnl_cd,
        CAST(NULL AS STRING) AS sls_terr_cd,
        CAST(NULL AS STRING) AS sls_rep_cust_key,
        CAST(NULL AS STRING) AS addr_type_cd,
        CAST(NULL AS STRING) AS hfm_entity_key,
        CAST(NULL AS STRING) AS hfm_entity_cd,
        CONCAT('msd_qad_', LOWER(ad_domain), '|', cntry_hier_key) AS deflt_delvr_cntry_key,
        ad_ctry AS deflt_delvr_cntry_cd,
        CAST(NULL AS STRING) AS trade_chnl_cd,
        CASE
            WHEN ad_addr LIKE 'Z%' OR ad_addr LIKE 'TM%' THEN 'IC'
            ELSE '3rd'
        END AS inter_co_cd
    FROM base_data
)
SELECT *
FROM transformed_data;